# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pedidos_pb2 as pedidos__pb2


class PedidosStub(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearOrden = channel.unary_unary(
                '/pedidos.Pedidos/CrearOrden',
                request_serializer=pedidos__pb2.Orden.SerializeToString,
                response_deserializer=pedidos__pb2.RespuestaOrden.FromString,
                )
        self.ConsultarOrden = channel.unary_unary(
                '/pedidos.Pedidos/ConsultarOrden',
                request_serializer=pedidos__pb2.QueryOrden.SerializeToString,
                response_deserializer=pedidos__pb2.RespuestaOrden.FromString,
                )


class pedidosSPrvicer(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def CrearOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pedidosSPrvicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearOrden,
                    request_deserializer=pedidos__pb2.Orden.FromString,
                    response_serializer=pedidos__pb2.RespuestaOrden.SerializeToString,
            ),
            'ConsultarOrden': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarOrden,
                    request_deserializer=pedidos__pb2.QueryOrden.FromString,
                    response_serializer=pedidos__pb2.RespuestaOrden.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedidos.Pedidos'P rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pedidos(Pbject):
    """------------------------------
    Servicios
    ------------------------------

    """

    @staticmethod
    def CrearOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedidos.Pedidos/PrearOrden',
            pedidos__pb2.Orden.SerializeToString,
            pedidos__pb2.RespuestaOrden.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultarOrden(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedidos.Pedidos/PonsultarOrden',
            pedidos__pb2.QueryOrden.SerializeToString,
            pedidos__pb2.RespuestaOrden.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
